name: coletar seguidores

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          Rscript -e 'install.packages("httr", repos="https://cloud.r-project.org")'
          Rscript -e 'install.packages("jsonlite", repos="https://cloud.r-project.org")'

      - name: Run script
        run: Rscript coleta_instagram.R

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "update followers" || echo "no changes"
          git push
